import{a as S,S as q,i as c}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const x="49034890-15d0e202b9bb59c7b310d7a4f",B="https://pixabay.com/api/";async function f(o,t){const s={key:x,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await S.get(B,{params:s})).data}const m=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more"),M=new q(".gallery a");function h(o){const t=o.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:i,comments:w,downloads:v})=>`
        <li class="gallery-item" style="list-style: none;">
          <a href="${n}">
            <img src="${s}" alt="${e}" loading="lazy" style="width: 100%; height: auto; display: block; border-radius: 4px;" />
          </a>
          <div class="info" style="display: flex; justify-content: space-around; padding: 8px 0; font-size: 14px;">
            <p><b>Likes:</b> ${r}</p>
            <p><b>Views:</b> ${i}</p>
            <p><b>Comments:</b> ${w}</p>
            <p><b>Downloads:</b> ${v}</p>
          </div>
        </li>
      `).join("");m.insertAdjacentHTML("beforeend",t),M.refresh()}function $(){m.innerHTML=""}function g(){p.classList.remove("hidden")}function b(){p.classList.add("hidden")}function L(){y.classList.remove("hidden")}function d(){y.classList.add("hidden")}const E=document.querySelector(".form"),P=document.querySelector(".load-more");let l="",a=1,u=0;E.addEventListener("submit",async o=>{if(o.preventDefault(),l=o.target.elements["search-text"].value.trim(),!!l){$(),d(),a=1,g();try{const t=await f(l,a);if(u=t.totalHits,t.hits.length===0){c.info({message:"No images found."});return}h(t.hits),u>15&&L()}catch{c.error({message:"Something went wrong."})}finally{b()}}});P.addEventListener("click",async()=>{a+=1,g(),d();try{const o=await f(l,a);h(o.hits);const t=Math.ceil(u/15);a>=t?(c.info({message:"We're sorry, but you've reached the end of search results."}),d()):L(),O()}catch{c.error({message:"Failed to load more images."})}finally{b()}});function O(){const o=document.querySelector(".gallery li");if(!o)return;const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
